---
- name: Mac Maker Profile Installer
  hosts: localhost
  connection: local

  handlers:
    - name: Load Handlers
      ansible.builtin.import_tasks: "handlers/main.yml"

  pre_tasks:
    - name: Run Pre-Install Tasks
      ansible.builtin.include_tasks: "tasks/pre_install.yml"

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
      vars:
        homebrew_brewfile_dir: "{{ variant_homebrew_brewfile_dir }}"
        homebrew_use_brewfile: "{{ variant_homebrew_use_brewfile }}"
    - role: osx_provisioner.homebrew_retry
      vars:
        brew_casks: "{{ variant_brew_casks }}"
        brew_packages: "{{ variant_brew_packages }}"
        brew_taps: "{{ variant_brew_taps }}"
        brew_targeted_casks: "{{ variant_brew_targeted_casks }}"
        brew_targeted_casks_location: "{{ variant_brew_targeted_casks_location }}"
    - role: osx_provisioner.homebrew_retry
      vars:
        brew_casks: []
        brew_packages: []
        brew_taps: []
        brew_targeted_casks: "{{ alternate_brew_targeted_casks }}"
        brew_targeted_casks_location: "{{ alternate_brew_targeted_casks_location }}"
    - role: osx_provisioner.clamav
    - role: osx_provisioner.homeshick
    - role: osx_provisioner.asdf
    - role: osx_provisioner.symlinks
      vars:
        symlinks: "{{ variant_symlinks }}"
    - role: osx_provisioner.downloader
    - role: niall_byrne.ansible_role_osx_defaults

  post_tasks:
    - name: Run Post-Install Tasks
      ansible.builtin.include_tasks: "tasks/post_install.yml"
