---
- name: Add Colima Symlink
  become: true
  ansible.builtin.file:
    src: "/Users/{{ brew_user }}/.colima/default/docker.sock"
    dest: /var/run/docker.sock
    mode: "0751"
    owner: "root"
    group: "daemon"
    state: link
    follow: false
    force: true
  notify:
    - "Enable Colima"

- name: Add Colima Launch Script
  become: true
  ansible.builtin.copy:
    src: ./files/colima-start-fg.sh
    dest: /usr/local/bin/colima-start-fg.sh
    mode: "0755"
    owner: "{{ brew_user }}"
    group: "staff"
  notify:
    - "Enable Colima"

- name: Add LaunchAgents Folder
  become: true
  ansible.builtin.file:
    dest: /Users/{{ brew_user }}/Library/LaunchAgents
    mode: "0700"
    owner: "{{ brew_user }}"
    group: "staff"
    state: "directory"
  notify:
    - "Enable Colima"

- name: Add Colima Launch Agent
  become: true
  ansible.builtin.copy:
    src: ./files/com.github.abiosoft.colima.plist
    dest: /Users/{{ brew_user }}/Library/LaunchAgents/com.github.abiosoft.colima.plist
    mode: "0644"
    owner: "{{ brew_user }}"
    group: "staff"
  notify:
    - "Enable Colima"
