---
- name: Reshim asdf
  become: true
  become_user: "{{ asdf_user }}"
  ansible.builtin.command: "bash -lc 'source {{ asdf_source }}; asdf reshim python'"
  changed_when: true
  args:
    chdir: "{{ asdf_user_home }}"

- name: Restart Dock
  ansible.builtin.command: killall Dock
  changed_when: true

- name: Restart SystemUIServer
  ansible.builtin.command: killall SystemUIServer
  changed_when: true

- name: Globally Enable Firewall
  become: true
  ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
  changed_when: true
  listen: "Enable Firewall"

- name: Enable Colima
  community.general.launchd:
    name: "com.github.abiosoft.colima"
    enabled: true
    state: started
    force_stop: yes
  listen: "Enable Colima"

- name: Enable Stealth Mode
  become: true
  ansible.builtin.command: /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on
  changed_when: true
  listen: "Enable Firewall"

- name: Enable Packet Filter
  become: true
  community.general.launchd:
    name: "user.pfctl"
    enabled: true
    state: started
    force_stop: yes
  listen: "Enable Firewall"
