---
- name: Load Common Variables
  ansible.builtin.include_tasks: "pre_install/01-vars.yml"

- name: Perform Compatibility Test
  ansible.builtin.include_tasks: "pre_install/02-compatibility.yml"

- name: Load Variant
  ansible.builtin.include_tasks: "pre_install/10-variant.yml"
