---
# Configure fstab to gnore specific disks on startup, to prevent osx from prompting to decrypt them.

- name: Template fstab to ignore the audio disk on startup
  become: True
  ansible.builtin.template:
    src: ./templates/fstab.j2
    dest: /etc/fstab
    owner: root
    group: wheel
    mode: "0644"
