---
# Move data directories to the project disk to help keep the system disk size small

- name: Patch Disk - Create Poetry Data Directory
  ansible.builtin.file:
    path: "{{ patch_poetry_new_dir }}"
    owner: "{{ patch_user }}"
    mode: '0755'
    state: 'directory'
  tags:
    - patch

- name: Patch Disk - Patch Poetry Cache Directory
  ansible.builtin.file:
    dest: "{{ patch_poetry_old_dir }}"
    src: '{{ patch_poetry_new_dir }}'
    owner: "{{ patch_user }}"
    mode: '0755'
    state: 'link'
  tags:
    - patch
