---
# Populate the dock using dockutil.

- name: Dock - Reset Dock to Defaults
  community.general.osx_defaults:
    domain: com.apple.dock
    state: absent
    key: .
  notify:
    - Restart Dock
  tags:
    - dock

- name: Dock - Clear All Items
  ansible.builtin.command: "/bin/bash -lc 'dockutil --remove all'"
  changed_when: true
  notify:
    - Restart Dock
  tags:
    - dock

- name: Dock - Add Items
  ansible.builtin.shell: "sleep {{ dock_command_timeout }}; /bin/bash -lc 'dockutil {{ item }}'"
  changed_when: true
  with_items: "{{ dock_customizations }}"
  notify:
    - Restart Dock
  tags:
    - dock
